### ISSUE TITLE
Discuss and create teams

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#1]
[Teams ](https://github.com/orgs/OpenEnergyPlatform/teams) are used to group people and grant permissions:

- **admin** GitHub administration
- **developer** OEP developer
- **reviewer** OEP and data reviewer
- **steering-committee** Planning and decision making

Also check and include the material from 
https://github.com/oemof/organisation/issues/3
https://github.com/oemof/organisation/issues/23

**Comment by klarareder** [comment]
* normal user (upload, download and view data)

**Comment by Ludee** [comment]
We decided for additional teams. Please document and implement @christian-rli

**Comment by christian-rli** [comment]
Teams mentioned here are created. Closing this on older referenced issues accordingly. Further implementation and notes are going to take place in #27 .
