### ISSUE TITLE
[metadata] Diferentiate between different types of "contributions"

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#16]
There are different kinds of contributions:
1. Contribution in the creation of the data
1. Official release date #12 
1. Modification of the data
1. Modification of the metadata

Do we want to save the type of contribution. If yes, how?

**Comment by klarareder** [comment]
I think it is nice to see the type of contribution but not necessary. But it all depends on how shall that be displayed and in what detail. I could think of a button/tab/other for each table called something like 'changes made' which opens a table which gives an overview with:
 version, date, contributer, kind of contribution, in detail what was modified in this table, ...

**Comment by wingechr** [comment]
I think we should keep the information. Probably in form of a log table, like
timestamp, user, object, type_of_modification

**Comment by Ludee** [comment]
Result of a short discussion:
* Not possible to differentiate between "creation" and "modification"
* Each contribution has a "date", no "official_release_date" necessary
* We include the modification object

**object**:
- metadata
- data
