### ISSUE TITLE
[metadata] Check data package requirements

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#23]
http://frictionlessdata.io/specs/data-package/#required-properties

- [x] include "name"
- [x] validate with [python package](https://github.com/frictionlessdata/datapackage-py)

**Comment by christian-rli** [comment]
validated string with python datapackage-py (https://github.com/frictionlessdata/datapackage-py) current version is not compatible. Specific shortcomings are: 
- "A Contributor MUST have a title property and MAY contain path, email, role and organization properties." (https://frictionlessdata.io/specs/data-package/) . The current version only had a name. Other properties are than those mentioned were accpeted. i changed all occurences of "name" in contributors to "title"
 - resources property must have a path (https://frictionlessdata.io/specs/data-resource/). The current version did not specify one, as all resources are tables in oep. I included a path to the github repository of the json string itselt.

The strings that were made compatible in the described way are upoloaded in the examples repository (commit: https://github.com/OpenEnergyPlatform/examples/commit/e662364222b7a094cec1159577de0e49781c986d)
