### ISSUE TITLE
OEP developer group

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#27]
Assign and document roles for the organisation.
"Product Owner"
"Concept Owner"
"Developer"
"Tester"

**Comment by Ludee** [comment]
This issue is linked to #1

**Comment by christian-rli** [comment]
I created 

- [x] Product Owner (@Ludee )
- [x] "Concept Owner" (@MGlauer )
- [x] "Developer" (everyone)
- [ ] "Tester" ( @han-f  & @stap-m could you let me know the handles of your testers? I will close this issue, once I've added them to the team. Thank you)

**Comment by stap-m** [comment]
@Dhruvin14

**Comment by christian-rli** [comment]
I invited @Dhruvin14 and @vliste-oeko to to the Team "Tester" and can thereby close this issue.
