### ISSUE TITLE
Introduce term Open Energy Family  as a means to organise information better

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/organisation#29]
Open Energy Family can better describe the multitude of information that is available than openenergy-platform.

**Comment by han-f** [comment]
Idea: register openenergy-family.org and redirect to about page where a figure informs about all individual elements of the openenergy-family

**Comment by han-f** [comment]
![IMG_2740](https://user-images.githubusercontent.com/36844029/68850615-a340fc80-06d4-11ea-9357-6d9e5c7ab2bf.jpg)

**Comment by han-f** [comment]
As part of Hackathon on 2019-11-14 @stap-m @Ludee @han-f  changed the wording from OpenEnergyPlatform to Open Energy Family in repositories and readmes

**Comment by Ludee** [comment]
I just updated the Logo and will add it to this repo.

**Comment by han-f** [comment]
![Uploading IMG_2741.jpg…]()

**Comment by Ludee** [comment]
This idea was a great success! The OEFamily grows.
