### ISSUE TITLE
There should be a new OEP release

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/organisation#32]
We want to release a new version of the OEP. Therefore, we must update the parts of the OEFamily first. Specifically,

* Metadata v1.4.0 should be marked as a Release on github
* OMI needs a new release containing the finalized metadata v1.4
* OEP should get a new Release that uses OMI for metadata handling
* OEDIALECT should get a new release that yields the metadata functionality

I will create tickets in the corresponding repos, but as the whole picture is overarching, this is an issue for the organisation, too.

**Comment by jh-RLI** [comment]
@MGlauer Do you have an overview of the current status? We have done a lot of work since this issue was created. Perhaps we could collect the corresponding issues here?
