### ISSUE TITLE
Discuss, reorganise and rename GitHub-Teams

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#35]
The [GitHub-Teams](https://github.com/orgs/OpenEnergyPlatform/teams) are not well organised.
We use them for:

- OE-Family organisation (admin, developer)
- OEP development (Concept Owner, Product Owner, reviewer, Tester)
- OEO development (modelling-experts, ontology-experts, economy-experts, linked-open-data-experts, steering-committee)

Suggestion:
- add prefix to groups (oefamily, oep/oeo)
- harmonize spelling
- apply and document teams on a OEP page (e.g. tutorial)

**Comment by wingechr** [comment]
i like all three suggestions

**Comment by stap-m** [comment]
Sounds good to me. 
Concerning the sub-teams of the oeo development team, there will be a discussion at the next oeo developer meeting on experteses/teams. Maybe there are more changes coming...

**Comment by Ludee** [comment]
This is the outcome of the dev meeting:

- document here: https://github.com/OpenEnergyPlatform/ontology#teams-tag
    - prefixes 
    - harmonize spelling...

- ontology-experts (general ontology or oeo experts)
    - oeo:oeo-ontology-experts
    - oeo-formal-ontology-experts
    - oeo-steering-committee

- domain-experts (energy system modelers..)
    - economy
    - modelling
    - linked open data
    - geo & meteorology ?
    - energy system
    - energy / electricity market
    - modules? 

I will start the renaming now.

**Comment by Ludee** [comment]
I updated all team names and descriptions.
I appreciate feedback!

**Comment by Ludee** [comment]
I also went through the member lists and added and removed people.
Sorry for the spam if you were affected!

**Comment by christian-rli** [comment]
> I updated all team names and descriptions.
> I appreciate feedback!

I like the new naming system and approve of the dashes. I'm assuming that there is a reason behind the _general_ in _oeo-general-steering-committee_. Is that there in order to highlight the meta-level i.e. this isn't the actual steering committee, but the people who organize their meetings etc?

**Comment by Ludee** [comment]
That could have been meta but was an copy mistake.
Teams are done for now.
