### ISSUE TITLE
New Open Energy Family and OEP logos

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#37]
There is a draft for a new OEP logo that fits the design of the Open Energy Family.

**Comment by christian-rli** [comment]
Thank you @bmlancien ! My faourite is the classic website style logo, but I can make friends with the other ones as well. I propose using a ranked voting system to choose a winner. Maybe someone knows a simple tool for that? (For the record: online voting is a bad idea, unless it's not a secret election. So I'm presupposing that this would be an open election.)

**Comment by bmlancien** [comment]
After the feedback from the last meeting I did some new [sketches](https://sfile.iee.fraunhofer.de/ssf/s/readFile/folderEntry/37021830/8a8d8db574010a5c01752c81397318a0/1602769427000/last/OEP_Logo_Abstimmung_v2.png).

**Comment by wingechr** [comment]
looks good: my preference: 1, 2, 3, 5, 4

**Comment by klarareder** [comment]
Nice! I like the the "3D" ones: 3, 1, 2, 5, 4

**Comment by christian-rli** [comment]
the winner after a discussion and two-round system vote is number 5.
![winner](https://user-images.githubusercontent.com/42000429/99974770-af5ca100-2da1-11eb-9daf-37b96a89bcf7.png)
