### ISSUE TITLE
A documentation of the OEFamily is missing - Community Compendium

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#52]
We decide for **MkDocs** (over ReadTheDocs).
Start with a general description and describe all modules.

**Comment by jh-RLI** [comment]
I also found out about this tool. Quite similar to mkdocs but maybe even better https://docusaurus.io/

**Comment by jh-RLI** [comment]
I think readthedocs is overkill, I really want to go for the simplest solution.

**Comment by henhuy** [comment]
docusauraus looks nice, but I wanted to remark that you have to install node.js in order to use it.
Mkdocs is based on python only...

**Comment by jh-RLI** [comment]
That's true, I'm aware of that :) . Since apps like the oeo-viewer(react based app) are integrated in the oeplatform django project, we need nodejs anyway. So it is at least an option for the OEP. But if mkdocs is as easy, I don't mind, and it might fit better with RLI's know-how.

**Comment by jh-RLI** [comment]
Also we should add a OEF README that will be visible to the public and one that will be visible to members. This should help to guide people:
![image](https://user-images.githubusercontent.com/38939526/201132790-8540c34b-4e46-4cf5-a0bb-2446e2b40178.png)

![image](https://user-images.githubusercontent.com/38939526/201133120-bbc108bb-960c-461d-9f7e-70e1e111d3b4.png)
