### ISSUE TITLE
Collect and display information on developer meetings

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#56]
The regular developer meetings should be presented on the OEP.

In addition I would like to test an open round for new people to ask question or get a small introduction.
Inspired by: https://www.dalicc.net/join-our-open-dev-thursday-meetings/

**Comment by jh-RLI** [comment]
This is already available https://openenergyplatform.github.io/organisation/family_community/contact/

Do you still want to attempt to establish a open round?
i will close this issue ... maybe the open round is worth another issue.
