### ISSUE TITLE
[Compendium] Documenation for Scnearion Bundles & OEKG are missing

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#74]
The compendium page is still empty:

https://openenergyplatform.github.io/organisation/family_members/templates-and-specification/factsheets/

**Comment by jh-RLI** [comment]
I will start working on the pages. 

We also need to document the oekg ... also on these pages?

We have to be careful to describe only the general information in the compendium and add the technical documentation, e.g. in the oeplatform docs.

**Comment by Ludee** [comment]
I just started the compendium page. It would be great if you cover the technical documentation on the oeplatform docu! @jh-RLI

**Comment by jh-RLI** [comment]
@adelmemariani Can you please provide the inmage for the schema of the OEKG :) You can use the branch called `feature-74-factsheet-docs` . There is the folder` compendium/img` you can put the image there. Please also put the source file that can be used to edit the image and not only the .png file :)

**Comment by jh-RLI** [comment]
Use this document to document the structure of the oekg:

family_members/knowledge-representation/oekg/
