### ISSUE TITLE
Adjust naming to Open Energy Platform

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/organisation#8]
After some feedback from different people I suggest to eliminate the white space in the name.

Edit: The original name was **OpenEnergy Platform**. We decided to move to **Open Energy Platform**

**Comment by klarareder** [comment]
very good idea

**Comment by christian-rli** [comment]
While I strongly agree that the white space is not pretty, I recall @MGlauer wanted to keep it for beauty non-related reasons. We should discuss this again.

**Comment by bmlancien** [comment]
I also believe the white space should be eliminated. Although I find the minus a bit better, I think using camel case is the better solution for naming a platform.

'The RLI designer'
